pipeline {
    agent {
      label 'Docker'
    }    

    environment {

    DOCKERHUB_CREDENTIALS = credentials('Dockerhub')
     registry = "manojpadala/fronted-lms"
        registryCredential = 'Dockerhub'
        dockerImage = ''
    }

    stages {

        stage('Building the docker image') {
            steps {
                sh 'cd webapp && docker build -t manojpadala/fronted-lms .'
            }
        }
        stage('Logging into dockerhub account') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('pushing the docker image into dockerhub') {
            steps {
                  sh 'docker push manojpadala/fronted-lms'
            }
        }
        stage('Remove old docker images') {
             steps {
                 sh 'docker rmi -f manojpadala/fronted-lms'

            }
        }
         stage('Running on kubernetes') {
            steps {
                echo 'Deploying....'
                sh "cd webapp && kubectl apply -f deployment.yml"
                sh "cd webapp && kubectl apply -f service.yml"
                sh "kubectl rollout restart deployment konalms"
            }
        }
    }
}
